services:
  - type: web
    name: travelhub
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear && python manage.py migrate && python manage.py load_catalogs && python manage.py cargar_aerolineas
    startCommand: gunicorn --bind 0.0.0.0:$PORT travelhub.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: travelhub-db
          property: connectionString

  - type: worker
    name: travelhub-celery-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A travelhub worker --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: travelhub-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: travelhub-redis
          property: connectionString

  - type: worker
    name: travelhub-celery-beat
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A travelhub beat --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: travelhub-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: travelhub-redis
          property: connectionString

databases:
  - name: travelhub-db
    databaseName: travelhub
    user: travelhub

  - name: travelhub-redis
    plan: free
    maxmemoryPolicy: noeviction
